"use strict";

// electron/preload.ts
var import_electron = require("electron");
import_electron.contextBridge.exposeInMainWorld("electronAPI", {
  getUsers: () => import_electron.ipcRenderer.invoke("db:users:list"),
  createUser: (data) => import_electron.ipcRenderer.invoke("db:users:create", data),
  updateUser: (id, data) => import_electron.ipcRenderer.invoke("db:users:update", id, data),
  deleteUser: (id) => import_electron.ipcRenderer.invoke("db:users:delete", id),
  getProjects: () => import_electron.ipcRenderer.invoke("db:projects:list"),
  createProject: (data) => import_electron.ipcRenderer.invoke("db:projects:create", data),
  updateProject: (id, data) => import_electron.ipcRenderer.invoke("db:projects:update", id, data),
  deleteProject: (id) => import_electron.ipcRenderer.invoke("db:projects:delete", id),
  getStatuses: () => import_electron.ipcRenderer.invoke("db:statuses:list"),
  createStatus: (data) => import_electron.ipcRenderer.invoke("db:statuses:create", data),
  updateStatus: (id, data) => import_electron.ipcRenderer.invoke("db:statuses:update", id, data),
  deleteStatus: (id) => import_electron.ipcRenderer.invoke("db:statuses:delete", id),
  getPriorities: () => import_electron.ipcRenderer.invoke("db:priorities:list"),
  createPriority: (data) => import_electron.ipcRenderer.invoke("db:priorities:create", data),
  updatePriority: (id, data) => import_electron.ipcRenderer.invoke("db:priorities:update", id, data),
  deletePriority: (id) => import_electron.ipcRenderer.invoke("db:priorities:delete", id),
  getTasks: (includeArchived, includeGenerated) => import_electron.ipcRenderer.invoke("db:tasks:list", includeArchived, includeGenerated),
  getArchivedTasks: () => import_electron.ipcRenderer.invoke("db:tasks:archived"),
  createTask: (data) => import_electron.ipcRenderer.invoke("db:tasks:create", data),
  updateTask: (id, data) => import_electron.ipcRenderer.invoke("db:tasks:update", id, data),
  deleteTask: (id) => import_electron.ipcRenderer.invoke("db:tasks:delete", id),
  archiveTask: (id) => import_electron.ipcRenderer.invoke("db:tasks:archive", id),
  unarchiveTask: (id) => import_electron.ipcRenderer.invoke("db:tasks:unarchive", id),
  getRecurringTasks: () => import_electron.ipcRenderer.invoke("db:tasks:recurring"),
  generateNextOccurrence: (id) => import_electron.ipcRenderer.invoke("db:tasks:generate-next", id),
  generateAllOccurrences: (id) => import_electron.ipcRenderer.invoke("db:tasks:generate-all", id),
  // Data Portability
  exportJson: () => import_electron.ipcRenderer.invoke("db:export-json"),
  importJson: () => import_electron.ipcRenderer.invoke("db:import-json"),
  exportTasksCsv: () => import_electron.ipcRenderer.invoke("db:export-csv"),
  importTasksCsv: () => import_electron.ipcRenderer.invoke("db:import-csv"),
  exportTaskShare: (taskId) => import_electron.ipcRenderer.invoke("db:export-task-share", taskId),
  importShareLink: () => import_electron.ipcRenderer.invoke("db:import-share-link"),
  togglePomodoro: () => import_electron.ipcRenderer.invoke("pomodoro:toggle"),
  getDbPath: () => import_electron.ipcRenderer.invoke("db:getPath"),
  pickDbPath: () => import_electron.ipcRenderer.invoke("db:pickPath"),
  setTheme: (theme) => import_electron.ipcRenderer.invoke("theme:set", theme),
  getVersion: () => import_electron.ipcRenderer.invoke("app:getVersion"),
  openExternal: (url) => import_electron.ipcRenderer.invoke("app:openExternal", url),
  // Notes
  getNotebooks: () => import_electron.ipcRenderer.invoke("notes:notebooks:list"),
  createNotebook: (name) => import_electron.ipcRenderer.invoke("notes:notebooks:create", name),
  renameNotebook: (id, name) => import_electron.ipcRenderer.invoke("notes:notebooks:rename", id, name),
  deleteNotebook: (id) => import_electron.ipcRenderer.invoke("notes:notebooks:delete", id),
  setNotebookColor: (id, color) => import_electron.ipcRenderer.invoke("notes:notebooks:setColor", id, color),
  getNotes: (notebookId, sortBy) => import_electron.ipcRenderer.invoke("notes:list", notebookId, sortBy),
  getAllNotes: (sortBy) => import_electron.ipcRenderer.invoke("notes:listAll", sortBy),
  getNoteById: (id) => import_electron.ipcRenderer.invoke("notes:get", id),
  createNote: (notebookId, title) => import_electron.ipcRenderer.invoke("notes:create", notebookId, title),
  saveNote: (id, title, content) => import_electron.ipcRenderer.invoke("notes:save", id, title, content),
  trashNote: (id) => import_electron.ipcRenderer.invoke("notes:trash", id),
  restoreNote: (id) => import_electron.ipcRenderer.invoke("notes:restore", id),
  deleteNotePermanently: (id) => import_electron.ipcRenderer.invoke("notes:delete", id),
  getTrashedNotes: () => import_electron.ipcRenderer.invoke("notes:trashed"),
  searchNotes: (query) => import_electron.ipcRenderer.invoke("notes:search", query),
  togglePin: (id) => import_electron.ipcRenderer.invoke("notes:togglePin", id),
  getBacklinks: (title, excludeId) => import_electron.ipcRenderer.invoke("notes:backlinks", title, excludeId),
  getAllTags: () => import_electron.ipcRenderer.invoke("notes:tags:all"),
  getNoteTags: (noteId) => import_electron.ipcRenderer.invoke("notes:tags:getForNote", noteId),
  addTagToNote: (noteId, tagId) => import_electron.ipcRenderer.invoke("notes:tags:add", noteId, tagId),
  removeTagFromNote: (noteId, tagId) => import_electron.ipcRenderer.invoke("notes:tags:remove", noteId, tagId),
  createTag: (name) => import_electron.ipcRenderer.invoke("notes:tags:create", name),
  getNotesByTag: (tagId) => import_electron.ipcRenderer.invoke("notes:tags:notesByTag", tagId),
  deleteTag: (id) => import_electron.ipcRenderer.invoke("notes:tags:delete", id),
  searchNoteTitles: (query) => import_electron.ipcRenderer.invoke("notes:searchTitles", query),
  exportNoteAsMarkdown: (id) => import_electron.ipcRenderer.invoke("notes:exportMarkdown", id),
  openNotesHelp: () => import_electron.ipcRenderer.invoke("notes:openHelp"),
  getRecentNotes: (limit) => import_electron.ipcRenderer.invoke("notes:recent", limit),
  getNoteByTitle: (title) => import_electron.ipcRenderer.invoke("notes:getByTitle", title),
  duplicateNote: (id) => import_electron.ipcRenderer.invoke("notes:duplicate", id),
  // Mind Maps
  getMindMaps: () => import_electron.ipcRenderer.invoke("mindmap:list"),
  getMindMap: (id) => import_electron.ipcRenderer.invoke("mindmap:get", id),
  createMindMap: (name) => import_electron.ipcRenderer.invoke("mindmap:create", name),
  renameMindMap: (id, name) => import_electron.ipcRenderer.invoke("mindmap:rename", id, name),
  deleteMindMap: (id) => import_electron.ipcRenderer.invoke("mindmap:delete", id),
  saveMindMap: (id, nodes, edges) => import_electron.ipcRenderer.invoke("mindmap:save", id, nodes, edges),
  // Habits
  getHabits: () => import_electron.ipcRenderer.invoke("habits:list"),
  getHabit: (id) => import_electron.ipcRenderer.invoke("habits:get", id),
  createHabit: (data) => import_electron.ipcRenderer.invoke("habits:create", data),
  updateHabit: (id, data) => import_electron.ipcRenderer.invoke("habits:update", id, data),
  deleteHabit: (id) => import_electron.ipcRenderer.invoke("habits:delete", id),
  logHabit: (habitId, date, completed) => import_electron.ipcRenderer.invoke("habits:log", habitId, date, completed),
  getHabitLogs: (habitId, startDate, endDate) => import_electron.ipcRenderer.invoke("habits:logs", habitId, startDate, endDate),
  getHabitYearLogs: (habitId, year) => import_electron.ipcRenderer.invoke("habits:yearLogs", habitId, year),
  getHabitStats: (habitId) => import_electron.ipcRenderer.invoke("habits:stats", habitId),
  getWeeklyReview: () => import_electron.ipcRenderer.invoke("habits:weeklyReview"),
  logPomodoroSession: (durationMinutes) => import_electron.ipcRenderer.invoke("habits:pomodoroLog", durationMinutes),
  // Time Tracking
  startTimer: (taskId, note) => import_electron.ipcRenderer.invoke("time:start", taskId, note),
  stopTimer: (entryId) => import_electron.ipcRenderer.invoke("time:stop", entryId),
  stopRunningTimer: () => import_electron.ipcRenderer.invoke("time:stopRunning"),
  getRunningTimer: () => import_electron.ipcRenderer.invoke("time:running"),
  getTaskTime: (taskId, range) => import_electron.ipcRenderer.invoke("time:taskTime", taskId, range),
  getDailyReport: (date) => import_electron.ipcRenderer.invoke("time:dailyReport", date),
  getWeeklyReport: (startDate) => import_electron.ipcRenderer.invoke("time:weeklyReport", startDate),
  getTimeEntries: (taskId) => import_electron.ipcRenderer.invoke("time:entries", taskId),
  deleteTimeEntry: (id) => import_electron.ipcRenderer.invoke("time:delete", id),
  updateTimeEntry: (id, data) => import_electron.ipcRenderer.invoke("time:update", id, data),
  getTotalFocusToday: (date) => import_electron.ipcRenderer.invoke("time:totalToday", date),
  // Journal
  getJournalEntry: (date) => import_electron.ipcRenderer.invoke("journal:get", date),
  upsertJournalEntry: (date, data) => import_electron.ipcRenderer.invoke("journal:upsert", date, data),
  deleteJournalEntry: (date) => import_electron.ipcRenderer.invoke("journal:delete", date),
  getJournalRange: (start, end) => import_electron.ipcRenderer.invoke("journal:range", start, end),
  getJournalOnThisDay: (month, day, excludeDate) => import_electron.ipcRenderer.invoke("journal:onThisDay", month, day, excludeDate),
  getJournalDailyStats: (date) => import_electron.ipcRenderer.invoke("journal:dailyStats", date),
  getJournalSummaryReport: (start, end, criteria) => import_electron.ipcRenderer.invoke("journal:summaryReport", start, end, criteria),
  // Links
  getLinks: (filters) => import_electron.ipcRenderer.invoke("links:list", filters),
  getLink: (id) => import_electron.ipcRenderer.invoke("links:get", id),
  createLink: (data) => import_electron.ipcRenderer.invoke("links:create", data),
  updateLink: (id, data) => import_electron.ipcRenderer.invoke("links:update", id, data),
  deleteLink: (id) => import_electron.ipcRenderer.invoke("links:delete", id),
  getLinkCategories: () => import_electron.ipcRenderer.invoke("links:categories:list"),
  createLinkCategory: (name) => import_electron.ipcRenderer.invoke("links:categories:create", name),
  deleteLinkCategory: (id) => import_electron.ipcRenderer.invoke("links:categories:delete", id),
  // Flashcards
  getFlashcardDecks: () => import_electron.ipcRenderer.invoke("flashcard:decks:list"),
  createFlashcardDeck: (name, description) => import_electron.ipcRenderer.invoke("flashcard:decks:create", name, description),
  updateFlashcardDeck: (id, data) => import_electron.ipcRenderer.invoke("flashcard:decks:update", id, data),
  deleteFlashcardDeck: (id) => import_electron.ipcRenderer.invoke("flashcard:decks:delete", id),
  getFlashcards: (deckId) => import_electron.ipcRenderer.invoke("flashcard:list", deckId),
  createFlashcard: (deckId, front, back) => import_electron.ipcRenderer.invoke("flashcard:create", deckId, front, back),
  updateFlashcard: (id, data) => import_electron.ipcRenderer.invoke("flashcard:update", id, data),
  deleteFlashcard: (id) => import_electron.ipcRenderer.invoke("flashcard:delete", id),
  reviewFlashcard: (id, quality) => import_electron.ipcRenderer.invoke("flashcard:review", id, quality),
  getDueFlashcards: (deckId) => import_electron.ipcRenderer.invoke("flashcard:due", deckId),
  // Spreadsheets
  getSpreadsheets: () => import_electron.ipcRenderer.invoke("spreadsheet:list"),
  getSpreadsheet: (id) => import_electron.ipcRenderer.invoke("spreadsheet:get", id),
  createSpreadsheet: (name) => import_electron.ipcRenderer.invoke("spreadsheet:create", name),
  updateSpreadsheet: (id, data) => import_electron.ipcRenderer.invoke("spreadsheet:update", id, data),
  deleteSpreadsheet: (id) => import_electron.ipcRenderer.invoke("spreadsheet:delete", id),
  // Utilities
  showSaveDialog: (options) => import_electron.ipcRenderer.invoke("util:showSaveDialog", options),
  writeBinaryFile: (filePath, data) => import_electron.ipcRenderer.invoke("util:writeBinaryFile", filePath, data),
  closeWindow: () => import_electron.ipcRenderer.invoke("app:closeWindow"),
  // Draw (BETA)
  getDrawDiagrams: () => import_electron.ipcRenderer.invoke("draw:list"),
  getDrawDiagram: (id) => import_electron.ipcRenderer.invoke("draw:get", id),
  createDrawDiagram: (name) => import_electron.ipcRenderer.invoke("draw:create", name),
  renameDrawDiagram: (id, name) => import_electron.ipcRenderer.invoke("draw:rename", id, name),
  deleteDrawDiagram: (id) => import_electron.ipcRenderer.invoke("draw:delete", id),
  saveDrawDiagram: (id, data) => import_electron.ipcRenderer.invoke("draw:save", id, data),
  getDrawioUrl: () => "drawio://app/index.html?client=1&proto=json",
  // Ideas
  getIdeas: (filters) => import_electron.ipcRenderer.invoke("ideas:list", filters),
  getIdea: (id) => import_electron.ipcRenderer.invoke("ideas:get", id),
  createIdea: (data) => import_electron.ipcRenderer.invoke("ideas:create", data),
  updateIdea: (id, data) => import_electron.ipcRenderer.invoke("ideas:update", id, data),
  deleteIdea: (id) => import_electron.ipcRenderer.invoke("ideas:delete", id),
  getRecentIdeas: (limit) => import_electron.ipcRenderer.invoke("ideas:recent", limit),
  getIdeaDocuments: (ideaId) => import_electron.ipcRenderer.invoke("ideas:documents:list", ideaId),
  addIdeaDocument: (ideaId, filename, data, mimeType) => import_electron.ipcRenderer.invoke("ideas:documents:add", ideaId, filename, data, mimeType),
  deleteIdeaDocument: (id) => import_electron.ipcRenderer.invoke("ideas:documents:delete", id),
  getIdeaUpdates: (ideaId) => import_electron.ipcRenderer.invoke("ideas:updates:list", ideaId),
  addIdeaUpdate: (ideaId, content, updateType) => import_electron.ipcRenderer.invoke("ideas:updates:add", ideaId, content, updateType),
  getIdeaTags: (ideaId) => import_electron.ipcRenderer.invoke("ideas:tags:get", ideaId),
  addTagToIdea: (ideaId, tagId) => import_electron.ipcRenderer.invoke("ideas:tags:add", ideaId, tagId),
  removeTagFromIdea: (ideaId, tagId) => import_electron.ipcRenderer.invoke("ideas:tags:remove", ideaId, tagId),
  getAllIdeaTagMappings: () => import_electron.ipcRenderer.invoke("ideas:tags:all-mappings"),
  // Focus Mode
  toggleFocus: () => import_electron.ipcRenderer.invoke("focus:toggle"),
  // AI Chat
  getConversations: () => import_electron.ipcRenderer.invoke("ai:chat:conversations:list"),
  createConversation: (provider, model, apiKey) => import_electron.ipcRenderer.invoke("ai:chat:conversations:create", provider, model, apiKey),
  deleteConversation: (id) => import_electron.ipcRenderer.invoke("ai:chat:conversations:delete", id),
  renameConversation: (id, title) => import_electron.ipcRenderer.invoke("ai:chat:conversations:rename", id, title),
  updateConversationConfig: (id, provider, model, apiKey) => import_electron.ipcRenderer.invoke("ai:chat:conversations:updateConfig", id, provider, model, apiKey),
  getMessages: (id) => import_electron.ipcRenderer.invoke("ai:chat:messages:list", id),
  deleteMessage: (id) => import_electron.ipcRenderer.invoke("ai:chat:messages:delete", id),
  deleteMessagesAfter: (conversationId, afterId) => import_electron.ipcRenderer.invoke("ai:chat:messages:delete-after", conversationId, afterId),
  sendChatMessage: (conversationId, message) => import_electron.ipcRenderer.send("ai:chat:send", { conversationId, message }),
  retryChatMessage: (conversationId) => import_electron.ipcRenderer.send("ai:chat:retry", { conversationId }),
  cancelChat: (conversationId) => import_electron.ipcRenderer.send("ai:chat:cancel", conversationId),
  onChatChunk: (callback) => {
    const handler = (_e, data) => callback(data);
    import_electron.ipcRenderer.on("ai:chat:chunk", handler);
    return () => import_electron.ipcRenderer.removeListener("ai:chat:chunk", handler);
  },
  getAiConfig: () => import_electron.ipcRenderer.invoke("ai:chat:config:get"),
  setAiConfig: (config) => import_electron.ipcRenderer.invoke("ai:chat:config:set", config),
  getOllamaModels: () => import_electron.ipcRenderer.invoke("ai:chat:ollama-models")
});
